config/routes.rb
Cw::Application.routes.draw do
	resources :users
	resources :sessions, only: [:new, :create, :destroy]
	resources :articles

	match '/signin',		to: 'sessions#new'
	match '/signout',		to: 'sessions#destroy'#, via: :delete
	match "articles/:id/version", to: 'articles#show'

	root to: 'static_pages#home'

	match '/help', to: 'static_pages#help' 

  get "articles/new" #is there a reason I left these two 'duplicate'
 	get "articles/show" #routes in here?

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :content

	has_paper_trail

	validates :title, 	presence: true, uniqueness: true
	validates :content, presence: true, uniqueness: true

#	def show_past_versions
#		self.versions.each do |version|
#			unless version.reify.nil?
#				link_to "Version {version.id}", version.reify
#			end
#		end
#	end 			



end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
	has_secure_password

	before_save { |user| user.email = email.downcase }
	before_save :create_remember_token




	validates :name, 	presence: true, length: { maximum: 50 }
	validates :email, presence: true, uniqueness: { case_sensitive: false }
	validates :password, presence: true, length: { minimum: 6 }
	validates :password_confirmation, presence: true

	private

		def create_remember_token
			self.remember_token = SecureRandom.urlsafe_base64
		end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
	include SessionsHelper


	# Force signout to prevent CSRF attacks
	def handle_unverified_request
		sign_out
		super
	end





end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_filter :signed_in_user, only: [:new, :update, :edit, :create, :destroy]

	def show
		@article = Article.find(params[:id])
		@versions = @article.versions
		@article = @article.versions[params[:version].to_i].reify if params[:version]
		#show!
	end

#	def show_versions
#		@article = Article.find(params[:id])
#		@all_versions = @article.versions
#	end	
#
#	def show_one_version(idx)
#		@version = @article.versions[idx]
#		#version_link = view_context.link_to(""	versions_show_version_path		 
#	end

	def index
		@articles = Article.all

	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(params[:article])
		if @article.save
			flash[:sucess] = "Hey, way to go on that new article, it looks really great!"
			redirect_to @article
		else
			render 'new'
		end

	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])

		if @article.update_attributes(params[:article])
			flash[:success] = "Article updated"
			redirect_to @article
		else
			render 'edit'
		end
	end


	def destroy
	end










	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end


	def create
		user = User.find_by_email(params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_to root_path
		else
			flash.now[:error] = 'Invalid email/password combination'
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_path
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
		@user = User.find(params[:id])
	end

	def new
  end
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController

	def index
		@versions = Version.all
	end

	def show_version
		@version = Version.find(params[:id])
		@version.reify
	end

	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end
	
	def current_user
		@current_user ||= User.find_by_remember_token(cookies[:remember_token])
	end

	def current_user?(user)
		user == current_user
	end

	def signed_in_user
		unless signed_in?
			store_location
			redirect_to signin_url, notice: "Please sign in."
		end
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		sessions.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.url
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/articles/_article.html.erb
<li>

	<%= link_to article.title, article %>


</li>

app/views/articles/_article_form.html.erb
<div class="container">
	<div class="span12">
		<%= form_for(@article) do |f| %>

			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label "Title" %>
			<%= f.text_field :title %>
		
			<%= f.label "Content" %>
			<%= f.text_area :content %>
		
				<br>
			<%= f.submit "Create Article", class: "btn btn-large btn-primary" %>
		<% end %>

		<!--<% if @article.errors.any? %>
			<div id="error_explanation">
				<ul>
					<% @article.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div<
		<% end %>-->


	</div>
</div>


	

app/views/articles/edit.html.erb
<% provide(:title, "Edit article") %>
<h1>Edit Article</h1>
<% if signed_in? %>


			<%= render 'articles/article_form' %>


<% else %> 
	<p>
		You must be a registered user to add or edit articles.
	</p>
<% end %>

app/views/articles/index.html.erb
<%= provide(:title, 'All articles') %>
<h1>All articles</h1>

<% if signed_in? %>
	<p><%= link_to "New Article", new_article_path,
				 class: "btn btn-success"  %></p>
	<br>
<% end %>

<ul class="articles">
	<%= render @articles %>
</ul>

app/views/articles/new.html.erb
<% provide(:title, "New Article") %>
<h1>New Article</h1>
<% if signed_in? %>


			<%= render 'articles/article_form' %>


<% else %> 
	<p>
		You must be a registered user to add or edit articles.
	</p>
<% end %>

app/views/articles/show.html.erb
<% provide(:title, @article.title) %>

<div class="container">
	<div class="span8">
		<h3><%= @article.title %></h3>
		<p><%= @article.content.html_safe %></p>

		<br>
<p>
<% unless @article.versions.first.originator.nil? %>
	Created by: <%= User.find_by_id(@article.versions.first.originator).name %></p>
<% end %>
	

<p>
<% unless @article.originator.nil? %>
	Last updated by: <%=  User.find_by_id(@article.originator).name %></p>
<% end %>

<% if signed_in? %>
		<p><%= link_to "Edit Article", edit_article_path %></p>
<% end %>
</p>
	</div>


	<p>Versions: <%= @article.versions.size %></p>
<!--<p>View version:
if @article.versions.any? %>
	@article.versions.each do |version|-->



	<ul><%= render "layouts/version" %></ul>



</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="#">Compiere Wiki</a>
	</small>
	<nav>
		<ul>
			<li><%= link_to "Staging", 		'http://184.169.143.80/apps/Compiere.html#home' %></li>
			<li><%= link_to "Production",	'http://184.168.143.131/apps/Compiere.html#home' %></li>
	
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
		<nav>
		<ul class="nav pull-left">
			<li><%= link_to image_tag("Compiere_logo_black_small.png", alt: "Compiere"), '#'%></li>
			</ul>
		</nav>
		<!--<%= link_to "Compiere Wiki", root_path, id: "logo" %>-->	
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Articles", articles_path %></li>
					<li><%= link_to "Home", 		root_path %></li>
					<li><%= link_to "Help",			help_path %></li>
					<% if signed_in? %>
	
					<!--	<li id="fat-menu" class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><%= link_to "Profile", current_user %></li>

								<li class="divider"></li>-->
								<li>
								<%= link_to "Sign out", signout_path, method: "delete" %>
								</li>
							<!--</ul>
						</li>-->
					<% else %>
						<li><%= link_to "Sign in", signin_path %></li>
					<% end %>		
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->

app/views/layouts/_version.html.erb
<% if !@versions.empty? %>
	<h3>Latest Version: <%= @versions.length %></h3>	
	<b>Version <%= "#{@versions.length}" %> Created At: </b><br>
	<%= @versions.last.created_at %><br>
	<b>By:</b> <%= @versions.last.whodunnit %><br>
		<% if params[:version] %>
			<h3>Viewing Version: <%= "#{params[:version]}" %></h3>		
			<b>Version <%= "#{params[:version]}" %> Created at:</b><br>
			<%= @versions[(params[:version].to_i - 1)].created_at %><br>
			<b>By</b>:<%= @versions[(params[:version].to_i - 1)].whodunnit %><br>
			<%= link_to "Go to most recent version" %><br>
		<% end %>
	<% v_num = 1 %>
	<% if @versions.length.to_i > 1 %>	
		<% if params[:version].to_i > 1 || !params[:version] %>
			<b>Versions:</b></br>
			<% if params[:version].nil? %>	
				<% v_num = @versions.length.to_i - 1%>	
				<% @versions.each do %>
					<%= link_to "Version #{params[:version].to_i + v_num}", 
											{:version => (params[:version].to_i + v_num)} %> 
					<% v_num -= 1 %><br>	
				<% end %>
			<% else %>
				<% @versions.each do %>
					<%= link_to "Version #{@versions.length.to_i - v_num}", 
											{:version => (@versions.length.to_i - v_num)} %> 
					<% v_num += 1 %>
					<br>	
				<% end %>			
			<% end %>	
		<% end %>
	<% end %>
<% else %>
	<p>This item does not have any registered version.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  	<title>
ONPS Compiere Wiki- Compiere Knowledge, For the Benefit of All Mankind | <%=
		yield(:title) %>
		</title>
  	<%= stylesheet_link_tag    "application", media: "all" %>
  	<%= javascript_include_tag "application" %>
  	<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>

			<%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>








		<h1>Help</h1>
		<p>
		I'm not sure what you could possibly need help with.  However, if you insist,
		you may contact me at 
		<a href="mailto:miless@onlynaturalpet.com">miless@onlynaturalpet.com</a>, and I
		will eventually reply.
		</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<!--<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>-->

<div class="center hero-unit">
	<h1>The ONPS Compiere<sup><small><strong>&#174</strong></small></sup> Wiki</h1>

	<h2>
		Like a Library of Alexandria that hasn't been burned down yet.
	</h2>
	<div class="span6 offset2">
		<%= link_to "Articles", 'articles', class: "btn btn-large btn-block btn-info" %>
	</div>
</div>


  

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<%= @user.name %><br>
<%= @user.email %>

app/views/versions/_version.html.erb
<!--<li>
link_to "Version #{@article.versions[idx]}", show_one_version(idx)</li>-->